Added Automatic Migrations
Capstone-Team-C/IDD pull request #165
Opened 2020-06-03 21:22 UTC by ohyonghao

This adds automatic migrations to Appserver and AdminUI.

2020-06-03 21:24 UTC, ohyonghao commented
You can test this by viewing the _EFMigrationHistory table in ServerExplorer, creating an empty migration, running the server, then refreshing the table view to see that the migration was applied. Then reset the migration history by using `Update-Database` and giving it the title of the previous migration e.g. 2020052922027_Add-Guid. I found it simple to select the file in Solution explorer and then copy the name from Properties and remove the .cs.

2020-06-05 23:53 UTC, unstable-compound submitted a review, later dismissed
Only reviewed the code, did not test it. 

Ill give it a cursory approval in the case nobody gets to reviewing it

2020-06-05 23:56 UTC, Jbrusaw requested changes
Please add automatic migrations for the AdminUIUser as well. Should be something like

                using (var context = serviceScope.ServiceProvider.GetService<AdminUIUserContext>())
                {
                    context.Database.Migrate();
                }

2020-06-07 01:58 UTC, brialee approved these changes

2020-06-07 02:37 UTC, Jbrusaw approved these changes

2020-06-07 02:38 UTC, merged