Added eXprs documentation on how to download timeshet.
Capstone-Team-C/IDD pull request #167
Opened 2020-06-04 05:40 UTC by LarryChiem

Signed-off-by: Larry Chiem <clarry@pdx.edu>
If ya can figure out the "Drop Files anywhere..." box that isn't centered on mobile but is on desktop, please see if it can be fixed. Otherwise it works as is. 
![image](https://user-images.githubusercontent.com/15273129/83719068-2c753d80-a5eb-11ea-97fc-40617bff326d.png)

2020-06-04 08:43 UTC, iyves submitted a review, later dismissed
Moved the tip into a snackbar. Looks good.

2020-06-06 05:40 UTC, ohyonghao requested changes
I don't see the tip show up on desktop. Scratch that, had to reload the app, do see it at the very bottom.

2020-06-06 05:40 UTC, ohyonghao commented on PWA/src/plugins/i18n.js
> +    close: '否',
Incorrect Chinese translations. Not sure why close was added, but the two translations for no and close should be swapped, no says to close something, and close says no.

2020-06-06 06:34 UTC, ohyonghao approved these changes

2020-06-06 06:46 UTC, merged