Prevented last row of table from being removed
Capstone-Team-C/IDD pull request #172
Opened 2020-06-06 03:58 UTC by brialee

Prevents the last row of a table from being removed if it is likely to be a total units row.

Signed-off-by: Brian Lee <brialee@pdx.edu>

2020-06-06 05:14 UTC, ohyonghao requested changes
Seems to work on the sheet I tested, though I think if the last row is not the total miles then we should replace that with something else, perhaps 0. It doesn't matter too much as the PWA calculates it based off the rows anyways.

2020-06-06 05:14 UTC, ohyonghao commented on Appserver/FormSubmit/AbstractFormObject.cs
> +    public static bool isTotalTimeRow(List<Cell> lastrow)
This should be in the derived class as a private non-static member

2020-06-06 05:14 UTC, ohyonghao commented on Appserver/FormSubmit/AbstractFormObject.cs
> +    public static bool isTotalMilesRow(List<Cell> lastrow)
This should be in the derived class as a private non-static method

2020-06-07 02:33 UTC, unstable-compound submitted a review, later dismissed

2020-06-07 16:32 UTC, ohyonghao approved these changes

2020-06-07 16:40 UTC, merged